// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hefxezhjnaajtyvhsqdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZnhlemhqbmFhanR5dmhzcWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTQwNDgsImV4cCI6MjA2MDk3MDA0OH0.88xuThRXdeYQutkdNrJwRih0Ado_0cS3O9Fx3hn59cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);